[www]
; L'utilisateur et le groupe sous lesquels le service tourne
user = www-data
group = www-data

; Le port d'écoute (Crucial pour Inception)
; On n'utilise pas de socket (/run/php/php.sock) car Nginx est sur un autre container.
; On écoute sur le port 9000 sur toutes les interfaces réseau.
listen = 9000

; Configuration des processus (Dynamic est le standard)
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Indispensable pour que PHP puisse accéder aux variables d'environnement (DB_NAME, etc.)
clear_env = no