events {} # Section obligatoire même si vide

http {
    include /etc/nginx/mime.types; # Pour que le CSS/Images s'affichent bien

    server {
        # SSL configuration
        listen 443 ssl;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        # Root and index
        root /var/www/wordpress;
        server_name pamallet.42.fr;
        index index.php index.html index.htm;

        location / {
            try_files $uri $uri/ =404;
        }

        # Configuration pour WordPress (PHP)
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}